import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.css';
import { estaSesion } from '@/hooks/SessionUtil';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const autenticado = estaSesion();

  return (
    <html lang="en" style={{ height: '100%' }}>
      <body className="bg-primary text-white">
        <section className="container-fluid flex-grow-1">
          {children}
        </section>
      </body>
    </html>
  );
}