import { estaSesion } from '@/hooks/SessionUtil';
import 'bootstrap/dist/css/bootstrap.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const autenticado = estaSesion();

  return (
    <html lang="en" style={{ height: '100%' }}>
      <body style={{ backgroundImage: 'url("https://static.vecteezy.com/system/resources/previews/028/663/748/non_2x/ai-ai-generatedrealistic-4k-sky-with-serene-cumulus-clouds-nature-s-atmospheric-beauty-in-stunning-detail-ideal-for-calming-and-scenic-concepts-free-photo.jpeg")', backgroundSize: 'cover' }} className="bg-primary text-white">
        <section className="container-fluid flex-grow-1">
          {children}
        </section>
      </body>
    </html>
  );
}
